version: '3.8'

services:
  web:
    build: ./app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - hospital-management-fastapi/hospital/app
    ports:
      - 8002:8080